bcc: ''
cc: ''
ckeConfig: ca35f24f-3b84-451c-8fad-e00ccad35c45 # Basic
from: ''
fromName: ''
heading: 'When someone creates an account:'
instructions: ''
key: account_activation
plain: false
replyTo: ''
saveLogs: true
system: true
template: emails/template
