bcc: ''
cc: ''
ckeConfig: ca35f24f-3b84-451c-8fad-e00ccad35c45 # Basic
from: ''
fromName: ''
heading: 'When someone changes their email address:'
instructions: ''
key: verify_new_email
plain: false
replyTo: ''
saveLogs: true
system: true
template: emails/template
