bcc: ''
cc: ''
ckeConfig: ca35f24f-3b84-451c-8fad-e00ccad35c45 # Basic
from: ''
fromName: ''
heading: 'Guest submission'
instructions: ''
key: guestSubmission
plain: false
replyTo: ''
saveLogs: true
system: false
template: emails/template
