color: null
description: null
fieldLayouts:
  e4501095-b4b3-4d6a-a259-1067ac920825:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - dateUpdated
      - link
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-21T16:14:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3b496ef-7d2d-49b6-b5ab-4666efb167ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T16:49:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d20193d0-40d4-400c-bce2-93f5b8d757d0 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a811fb88-f25e-4369-807f-7966f3ec0888
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T16:18:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 37f07c62-371d-489f-84be-d2566168b572 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5109b7b-0629-4f8e-9f33-aae97f8a6132
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T16:18:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1180ca24-3298-4cf1-b341-f355e8805a5d # Background colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75467444-0485-4505-b9f6-98abaa0883e8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-21T16:18:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 021872fb-5e2c-4c7d-a616-afc7d970e1aa # Text colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e0ff20f-185e-426d-96ee-e4bee764626a
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 2bd78a5a-f3ec-493b-9117-03238d2d6e7f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-22T08:29:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c04aff30-42c4-40f2-b4d2-eb7ffd05d428 # Contributor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f271e518-4200-41e2-8688-05419932f79e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T08:43:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8ad44d3-2823-4bea-a767-b86a578768cd # Contributor link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef054e2-453b-4a34-a71f-6b9cfa36c2df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-22T08:43:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b8dc8a4-2ed7-4e21-8893-9aab2b603850 # Contributor email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0243b8a2-da12-4818-9620-ac2d204ce4dd
            userCondition: null
            warning: null
            width: 100
        name: Contributor
        uid: cafef8a0-0a1e-454f-a4bb-e7163cab22e9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-24T15:20:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ba376e5-616a-43ea-aea1-d6509a324de4 # SEO Metadata
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9437f6c1-013e-4f01-ad31-aeefba7f46ab
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 873cb33b-e7cb-4d7c-b681-a129553e8b9b
        userCondition: null
handle: submissions
hasTitleField: true
icon: null
name: Submissions
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
