altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4d1508da-2443-466d-a6e9-194f9d79e41f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-21T16:24:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a2fe7111-f280-41de-a28c-dcd17f2c150c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46feef37-a02a-4a2c-9230-c6c60819f22c
        userCondition: null
fs: uploads
handle: cards
name: cards
sortOrder: 1
subpath: cards
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
