columnSuffix: null
handle: textColour
instructions: null
name: 'Text colour'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
